name: rently
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  flutter_vector_icons: ^2.0.0
  http: ^1.4.0
  speech_to_text: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/item1.png
    - assets/images/item2.png
    - assets/images/item3.png
    - assets/images/item4.png
    - assets/images/item5.png
    - assets/images/visa.png
    - assets/images/paypal.png
    - assets/images/mastercard.png
    - assets/images/apple.png
